#!/usr/bin/env bash
#
# chkconfig: 3 99 99
# description: Ceict webapp server

usage()
{
    echo "Usage: ${0##*/} {start|stop|restart|cleancache|log|config|cacheconfig}"
    exit 1
}

[ $# -gt 0 ] || usage

findDirectory()
{
  local L OP=$1
  shift
  for L in "$@"; do
    [ "$OP" "$L" ] || continue 
    printf %s "$L"
    break
  done 
}

running()
{
  local PID=$(cat "$1" 2>/dev/null) || return 1
  kill -0 "$PID" 2>/dev/null
}

JETTY_RUN=$(findDirectory -w /var/run /usr/var/run /tmp)
CWS_PID="$JETTY_RUN/cws.pid"

ACTION=$1

# Check if anction is one of start, stop, restart
CWS_HOME=/opt/ceict-webapp-server
JAVA_HOME=$CWS_HOME/jre
JAVA=$JAVA_HOME/bin/java

JETTY_HOME=$CWS_HOME/jetty
JETTY_LOGS=$CWS_HOME/logs
JETTY_START=$JETTY_HOME/start.jar

DATA_DIR=/usr/share/ceict-webapp-data
GEOSERVER_DATA_DIR=$DATA_DIR/geoserver_data_dir
TMPDIR=${TMPDIR:-/tmp}

JAVA_OPTIONS=("-Xms512m -Xmx512m -Xmn256m -XX:PermSize=128m -XX:MaxPermSize=128m")
JAVA_OPTIONS+=("-Ddata.dir=$DATA_DIR")
JAVA_OPTIONS+=("-DGEOSERVER_DATA_DIR=$GEOSERVER_DATA_DIR")
JAVA_OPTIONS+=("-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false")
JAVA_OPTIONS+=("-Dcom.sun.management.jmxremote.authenticate=false-Dcom.sun.management.jmxremote.port=8008")
JAVA_OPTIONS+=("-Dcws.home=$CWS_HOME" "-Djetty.home=$JETTY_HOME" "-Djetty.logs=$JETTY_LOGS" "-Djava.io.tmpdir=$TMPDIR")

RUN_ARGS=(${JAVA_OPTIONS[@]} -jar "$JETTY_START")
RUN_CMD=("$JAVA" ${RUN_ARGS[@]})

case "$ACTION" in
  start)
	echo -n "Start ceict webapp server: "
    if type start-stop-daemon > /dev/null 2>&1 
    then
      if start-stop-daemon -S -p"$CWS_PID" -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
      then
        sleep 1
        if running "$CWS_PID"
        then
          echo "OK"
        else
          echo "FAILED"
        fi
      fi
    else
      if [ -f "$CWS_PID" ]
      then
        if running $CWS_PID
        then
          echo "Already Running!"
          exit 1
        else
          # dead pid file - remove
          rm -f "$CWS_PID"
        fi
      fi
    "${RUN_CMD[@]}" > /dev/null 1>/dev/null 2>/dev/null &
    disown $!
    echo $! > "$CWS_PID"
      echo "STARTED Jetty `date`" 
    fi
	;;
  stop)
	echo -n "Stop ceict webapp server: "
    if type start-stop-daemon > /dev/null 2>&1; then
      start-stop-daemon -K -p"$CWS_PID" -d"$JETTY_HOME" -a "$JAVA" -s HUP
      TIMEOUT=30
      while running "$CWS_PID"; do
        if (( TIMEOUT-- == 0 )); then
          start-stop-daemon -K -p"$CWS_PID" -d"$JETTY_HOME" -a "$JAVA" -s KILL
        fi
        sleep 1
      done
      rm -f "$CWS_PID"
      echo OK
    else
      PID=$(cat "$CWS_PID" 2>/dev/null)
      kill "$PID" 2>/dev/null
      TIMEOUT=30
      while running $CWS_PID; do
        if (( TIMEOUT-- == 0 )); then
          kill -KILL "$PID" 2>/dev/null
        fi
        sleep 1
      done
      rm -f "$CWS_PID"
      echo OK
    fi
	;;
  restart)
	echo -n "Restart ceict webapp server: "
	service cws stop
	echo -n ""
	service cws start
	;;
  cleancache)
    service cws stop
	rm -rf "$DATA_DIR"/*
	echo -n "Cache config files has been deleted."
	;;
  log)
	tail -f "$JETTY_LOGS"/`date +%Y_%m_%d`.stderrout.log
	;;
  config)
	vi "$CWS_HOME"/webapps/root/WEB-INF/classes/config.properties
	;;
  cacheconfig)
	vi "$DATA_DIR"/ROOT/config.properties
	;;
esac

exit 0
